// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgbQpNFj7HjfVgDP_co43VmibH4uDLu7E',
    appId: '1:346409028784:web:b736eedb9271429d443f75',
    messagingSenderId: '346409028784',
    projectId: 'whatsapp-backend-1da18',
    authDomain: 'whatsapp-backend-1da18.firebaseapp.com',
    storageBucket: 'whatsapp-backend-1da18.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaQ1hv2wrNULZOfV5I7FnMAUs3RfbZlHM',
    appId: '1:346409028784:android:72d3a81fd3da83d8443f75',
    messagingSenderId: '346409028784',
    projectId: 'whatsapp-backend-1da18',
    storageBucket: 'whatsapp-backend-1da18.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo6BhXjwMl3HBDXZ9yDrNgTGRMtNqXDwg',
    appId: '1:346409028784:ios:cab8c96d3bbf1395443f75',
    messagingSenderId: '346409028784',
    projectId: 'whatsapp-backend-1da18',
    storageBucket: 'whatsapp-backend-1da18.appspot.com',
    iosClientId: '346409028784-6unoae8v8cm4noknigjria5tnouao4jj.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo6BhXjwMl3HBDXZ9yDrNgTGRMtNqXDwg',
    appId: '1:346409028784:ios:cab8c96d3bbf1395443f75',
    messagingSenderId: '346409028784',
    projectId: 'whatsapp-backend-1da18',
    storageBucket: 'whatsapp-backend-1da18.appspot.com',
    iosClientId: '346409028784-6unoae8v8cm4noknigjria5tnouao4jj.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappClone',
  );
}
